version: '2.0'
services:
  reconflow:
    image: adarshshetty/reconflow:v1.0
    network_mode: 'host'
    cap_add:
      - NET_ADMIN
    volumes:
      - /reconflow:/reconflow
    container_name: reconflow
    environment:
      - 'TELEGRAM_BOT_TOKEN=xxx.xxx.xxx.xxx'
